version: '3.6'  
services:
  frontend:
    image: brunogamacatao/autenticacao_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: brunogamacatao/autenticacao_backend
    environment:
      - DATABASE_URL=mongodb://banco_de_dados/autenticacao
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
    depends_on: 
      - banco_de_dados
  banco_de_dados:
    image: mongo
